apps/the_blog/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='home' ),
    path('article/<slug:slug>', views.PostDetailView, name='article_detail'),
    path('article/<slug:slug>/delete/', views.DeletePostView.as_view(), name='delete_post'),
    path('article/edit/<slug:slug>/', views.UpdatePostView.as_view(), name='edit_post'),
    path('article/new/', views.AddPostView.as_view(), name='create_post'),
    path('search/', views.SearchPostsResultListView.as_view(), name='posts_search_results'),
    path('category/<slug:slug>', views.CategoryDetailView.as_view(), name='category')
]

simple_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 

# from markdownx import urls as markdownx

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('the_blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),

    # Django broswer reload
    path("__reload__/", include("django_browser_reload.urls")),

    # Django prose for text editing
    path("prose/", include("prose.urls")),

    # markdownx 
    # path('markdownx/', include(markdownx))
    # path('markdownx/', include('markdownx.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# urlpatterns += [
#     url(r'^markdownx/', include(markdownx))
# ]


handler404 = 'the_blog.views.error_404'

apps/the_blog/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.template.defaultfilters import slugify
from django.db.models.signals import pre_save

from markdownx.models import MarkdownxField
from markdownx.utils import markdownify

from .managers import PostManager
from simple_blog.utils import unique_slug_generator

from prose.fields import RichTextField
from prose.models import AbstractDocument

class Category(models.Model):
    category_name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=255, null=True, blank=True, editable=False)

    def __str__(self):
        return f"{self.category_name}"

    def get_absolute_url(self):
        return reverse('category', kwargs={'slug':self.slug})
    class Meta: 
        verbose_name = 'category'
        verbose_name_plural = 'categories'


def pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(pre_save_receiver, sender=Category)


class ArticleContent(AbstractDocument):
    pass
class Post(models.Model):
    title = models.CharField(max_length=255, unique=True)
    description = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    category = models.ForeignKey(
        Category, 
        on_delete=models.PROTECT,
        related_name='category',
        default=1
    )
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE,
        related_name='author',
        default=''
    )
    body = RichTextField()
    # body = models.OneToOneField(ArticleContent, on_delete=models.CASCADE)
    # body = MarkdownxField()
 
    # Post manager.
    objects = PostManager()


    def __str__(self):
            return f"{self.title} | {str(self.author).title()}"

    def get_absolute_url(self):
        return reverse('article_detail', kwargs={'slug':self.slug}) # args=[str(self.slug)]

    def save(self, *args, **kwargs): 
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    class Meta:
        ordering = ['-date_created']
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        
class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    commentator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    comment_body = MarkdownxField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def formatted_markdown(self):
        return markdownify(self.comment_body)

    def __str__(self):
        return f"{self.comment_body}| {self.post}"

    def get_absolute_url(self):
        return reverse('article_detail', kwargs={'pk':self.pk})

apps/the_blog/forms.py
from django import forms
from django.forms import widgets

from .models import Comment, Post, Comment


class CreatePostForm(forms.ModelForm):

    #field_order = ['body', 'title', 'description', 'author', 'category',]
    class Meta: 
        model = Post
        fields = ['title', 'description', 'body',]
    
        widgets ={
               'title': forms.TextInput(attrs={
                   'class':'form-control'
                   }),

               'description': forms.TextInput(attrs={
                   'class':'form-control'
                   }),

               'author': forms.TextInput(attrs={
                   'class':'form-control',  'type':'hidden'
                   }),

               'body': forms.Textarea(attrs={
                   'class':'form-control', 'rows': 18
                   }),
        }

class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'description', 'body',]

        widgets ={
               'title': forms.TextInput(attrs={
                   'class':'form-control'
                   }),

               'description': forms.TextInput(attrs={
                   'class':'form-control'
                   }),

               'body': forms.Textarea(attrs={
                   'class':'form-control', 'rows': 18
                   }),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_body',]

        widgets = {
            'comment_body': forms.Textarea(attrs={})
            }

        

apps/the_blog/views.py
from django.contrib.auth import get_user_model
from django.http.response import HttpResponseRedirect
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.shortcuts import get_object_or_404

from .models import Comment, Post, Category
from .forms import CommentForm, CreatePostForm, EditPostForm 

def error_404(request, exception):
    return render(request, '404.html')

class CategoriesListViewMixin():
    """
    Get all categories
    """
    def get_context_data(self, *args, **kwargs):
        categories = Category.objects.all()
        context = super().get_context_data(*args, **kwargs)
        context['categories'] = categories
        return context

class HomeView(CategoriesListViewMixin,ListView):
    model = Post
    template_name = 'home.html'
    context_object_name = 'post_list'
    paginate_by = 6


def PostDetailView(request, slug):
    post = get_object_or_404(Post, slug__iexact=slug)
    comments = Comment.objects.filter(
        post=post.id
        ).order_by('-id')

    all_author_post = Post.objects.filter(
        author=post.author.id
        ).exclude(slug=slug)
    categories = Category.objects.all()

    user = get_user_model()

    # comment output ======================
    # Refactor this function from here ==========
    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            content = request.POST.get('comment_body')
            comment = Comment.objects.create(
                post=post,
                commentator=request.user,
                comment_body=content
                )
            comment.save()
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form = CommentForm

    context = {
        'post':post,
        'all_author_post':all_author_post,
        'comments':comments,
        'comment_form':comment_form,
        'categories': categories
        }
    template = 'article_detail.html'
    return render(request, template, context)

class AddPostView(LoginRequiredMixin, CategoriesListViewMixin, CreateView):
    model = Post
    form_class = CreatePostForm
    template_name = 'create_post.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
        
class UpdatePostView(UserPassesTestMixin, CategoriesListViewMixin, UpdateView):
    model = Post
    form_class = EditPostForm
    template_name = 'update_post.html'

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

class DeletePostView(UserPassesTestMixin, CategoriesListViewMixin, DeleteView):
    model = Post
    # template_name = 'delete_post.html'
    template_name = 'article_detail.html'
    success_url = reverse_lazy('home')
   
    def test_func(self):
        '''
        Forbid a user from editing and deleting posts they
        did not create.
        '''
        obj = self.get_object()
        return obj.author == self.request.user


class SearchPostsResultListView(CategoriesListViewMixin, ListView):
    context_object_name = 'post_list'
    template_name = 'search_result.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        return Post.objects.search(query=query)

# class CategoriesListView(ListView):
#     model = Category
#     context_object_name = 'categories'
#     template_name = 'home.html'

class CategoryDetailView(CategoriesListViewMixin, DetailView):
    model = Category
    context_object_name = 'category'
    template_name = 'category.html'

    def get_context_data(self, *args, **kwargs):
        '''
        Get the posts related to each category
        '''
        category_slug  = self.kwargs['slug'].replace('-', ' ')
        categoryposts = Post.objects.select_related().filter(
            category__category_name__iexact=category_slug
            )
        context = super().get_context_data(*args, **kwargs)
        context['categoryposts'] = categoryposts
        return context

apps/the_blog/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/base.css' %}">

    <title>{% block title %}SoftDevBlog{% endblock title %}</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">SIMPLE BLOG</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            
            {% if category_menu %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Posts Categories
              </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  {% for category in category_menu %} 
                  <li><a class="dropdown-item" href="{% url 'category' category|slugify %}">
                      {{ category }}</a>
                  </li> 
                  {% endfor %}
                  <!-- <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li> -->
                </ul>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'category_list' %}">Posts Categories</a>
            </li>
            {% endif %}

            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'create_post' %}">+ New Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'add_category' %}">Add Category</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">{{ user.username.title }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>

            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}" tabindex="-1" aria-disabled="true">Login</a>
            </li>
            {% endif %}

          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>







            

    {% block content %}
    
    
    {% endblock content %}

    <!--<nav class="navbar bottom navbar-light bg-dark">
        <div class="container-fluid">
          FOOTER
        </div>
    </nav>-->
    



<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

apps/the_blog/templates/category.html
{% extends 'base.html' %}

{% block title %} Category {% endblock title %}

{% block content %}
{% load static %}


<div class="mt-12 md:mt-32 mb-16 px-5 lg:px-14 " tyle="border: 2px dotted red;">
   <h4 class="text-2xl text-center md:text-3xl text-heading-color">{{ category.category_name.title }}</h4>

   
   <div class="space-y-5 md:w-11/12 xl:w-10/12 mx-auto sm:space-y-0 mt-8 md:mt-14 sm:grid sm:grid-cols-2 lg:grid-cols-3 sm:gap-8 md:gap-6 "
       tyle="border: 2px solid yellow;">
       {% for post in categoryposts %} 
       <div 
           class="h56 mdw32 md:w2/5 bgwhite bg-primary-colo text-pry-font-color rounded-lg border border-gray-200 shadow-md "
           tyle="border: 2px solid red;">
           <!-- <a href="#">
               <img class="rounded-t-lg" src="{% static '/the_blog/media/boy_on_bed.png' %}" alt="">
           </a> -->
           <div class="p-5 min-h-full " tyle="border: 3px dotted blue;">
               <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray900 text-heading-color"> {{ post.title.title }}</h5>
               <!-- </a> -->
               <p class="mb-3 font-normal text-pry-font-color">
                   <!-- {{ post.description }} -->
                   {{ post.body|slice:":150" }}...
               </p>
             
               <a 
                   href="{% url 'article_detail' post.slug %}" 
                   class="inline-flex items-center py-2 px-3 text-sm font-medium 
                    text-center text-white bg-blue700 bg-primary-color rounded-lg hover:bg-blue-800
                     focus:ring-4 focus:outline-none focus:ring-blue-300 mt-3
                      "
                   >
                   Read
                   <svg aria-hidden="true" class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
               </a>
           </div>
       </div>
       {% endfor %}
   </div>
</div>
    
{% endblock content %}}

apps/the_blog/templates/create_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Create Blog Post {% endblock title %}

{% block content %}

{% if user.is_authenticated %}
    <div 
        class="mt-32 pl-32" 
    >

        <h2 class="">Add A New Post</h2>

        <form method="POST" class="w-4/6" tyle="border: 2px solid rgb(157, 0, 255);">
            {% csrf_token %}
            
            <label for="id_title">Title:</label>
    <input type="text" name="title" value="" class="form-control" maxlength="255" required id="id_title">
    
    
  </p>

  
  <p>
    <label for="id_description">Description:</label>
    <input type="text" name="description" value="" class="form-control" maxlength="255" required id="id_description">
    
    
  </p>

  <ul class="errorlist"><li>This field is required.</li></ul>
  <p>
    <label for="id_body">Body:</label>
    <div class="django-prose-editor-container">
  <input id="id_body" name="body" type="hidden" name="content"  />
  <trix-editor input="id_body" class="django-prose-editor trix-content h-64" data-upload-attachment-url="/prose/attachment/"></trix-editor>


            <button class="">Submit Post</button>
        </form>
        
        <div class="" tyle="border: 2px solid red;">
        {{ form.media }}
        </div>
    </div>


    {% else %}
    <h2>You do not have  access to this page</h2>

{% endif %}



{% endblock content %}

apps/the_blog/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<main class="px-6 pb-12">
    <div 
        class="space-y-4 md:space-y-16 lg:space-y-8 md:flex mt-9 md:pt-14 justify-around content-around" 
        tyle="border: 2px solid orange;"
    >
        <div 
            class="space-y-6 sm:px-0 xl:px-16 md:grow- md:w3/5 basis-3/6 md:pt-12 xl:pt-24" 
            tyle="border:2px solid green"
        >
            <h1 class="text-3xl sm:text-4xl font-bold sm:px-16 md:px-0 sm:text-center md:text-left">
                Lorem ipsum dolor sit consectetur elit.
            </h1>
            <p class="sm:px-10 md:px-0">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. 
                Fugiat cumque nulla temporibus accusantium s enim reiciendis! Sequi, expedita repudiandae.
            </p>
        </div>

        <div class="w2/4 basis-3/5 md:pl-16 xl:pr-16 " tyle="border: 3px dotted blue;">
            <img 
                class="block sm:hidden mx-auto w-full md:h-auto max-w- h-aut" 
                src="{% static '/the_blog/media/girl_texting.png' %}" 
                alt=""
            >
            <img 
                class="hidden sm:block mx-auto md:mt-1 md:mr-16 md:w-full rounded-md" 
                src="{% static '/the_blog/media/boy_on_bed.png' %}" 
                alt=""
            >
        </div>
    </div>


    <div class="mt-16 md:mt-24 lg:px-14">
        <h4 class="text-2xl md:text-3xl text-heading-color">Top Articles</h4>

        <div class="space-y-5 sm:space-y-0 mt-4 sm:grid sm:grid-cols-2 lg:grid-cols-3 sm:gap-8 md:gap-6"
            tyle="border: 2px solid yellow;">
            {% for post in post_list %}
            <div 
                class="h56 md:w32 bgwhite bg-primary-color text-white rounded-lg border border-gray-200 shadow-md "
                tyle="border: 2px solid red;">
                <!-- <a href="#">
                    <img class="rounded-t-lg" src="{% static '/the_blog/media/boy_on_bed.png' %}" alt="">
                </a> -->
                <div class="p-5 min-h-full" tyle="border: 3px dotted red;">
                    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray900 text-white"> {{ post.title.title }}</h5>
                    <!-- </a> -->
                    <p class="mb-3 font-normal text-gray-700 text-white/90">
                        <!-- {{ post.description }} -->
                        {{ post.body|slice:":150" }}...
                    </p>
                  
                    <a 
                        href="{% url 'article_detail' post.slug %}" 
                        class="inline-flex items-center py-2 px-3 text-sm font-medium 
                         text-center text-white bg-blue700 bg-primary-color2 rounded-lg hover:bg-blue-800
                          focus:ring-4 focus:outline-none focus:ring-blue-300 animate-bounce mt-3
                           "
                        >
                        Read
                        <svg aria-hidden="true" class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main>

{% endblock content %}

apps/the_blog/templates/search_result.html
{% extends 'base.html' %}

{% block title %} Search Results {% endblock title %}

{% block content %}


<h2> Results for {{ query.title }}</h2>


{% if post_list %}
    {% for post in post_list %}
        <div class="">
            <div class="">
                <div class="">
                    <div class="">
                        <h3 class="">
                            {{ post.title}}
                        </h3>
                        <p class="">
                            <strong>Author:</strong>
                            {{ post.author.first_name.title }} {{ post.author.last_name.title }}
                        </p>
                        <p class=''>
                            {{ post.description }}
                        </p>

                        <a href="{% url 'article_detail' post.slug %}" class="">
                            Read
                        </a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% else %}
    <h2>Empty Search</h2>
{% endif %}






{% endblock content %}

apps/the_blog/templates/update_post.html
{% extends 'base.html' %}

{% block title %} Edit Post {% endblock title %}

{% block content %}

{% if user.is_authenticated %}
    <div class="">
        <h2>Update Post</h2>

        <div class="">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="">Update</button>
            </form>

            <div class="">
            <p></p>
            {{ form.media }}
        </div>
        </div>
    </div>

    {% else %}
        <h2>You do not have  access to this page</h2>

    {% endif %}

    
{% endblock content %}